version: "3.7"

services:

  swagger-ui:
    image: savioli/britecore-api-specs:latest
    container_name: "swagger-ui"
    restart: always
    build: 
      context: .
      dockerfile: ./deploy/Dockerfile
    environment:
      SWAGGER_JSON: /specification/specification.yaml
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
    networks:
      - savioli

networks:
  savioli:
    driver: bridge