version: "3.7"

services:

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8081:8080"
    environment:
      SWAGGER_FILE: /specification/specification.yaml
    volumes:
      - ./specification:/specification

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /specification/specification.yaml
    volumes:
      - ./specification:/specification